title: "Luís Paulo Santos"
description: "Academic webpage · Publications · Projects · Lecturing · Students"
url: ""
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

locale: "en-US"

author:
  name: "Luís Paulo Santos"
  avatar: "/assets/images/lps.jpg"
  bio: "Associate Professor at the Department of Informatics (University of Minho) and senior researcher at INESC TEC."
  location: "Braga, Portugal"
  email: "psantos@di.uminho.pt"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

navigation: main
